UPLOAD_DIR = "uploads/"
SUPPORTED_FILE_EXTENSION = ["pdf", "txt", "docx", "doc", "csv"]
MAX_UPLOAD_SIZE_LIMIT = 25 * 1024 * 1024  # 25 MB

FILE_STATUS_PROCESSING = "PROCESSING"
FILE_STATUS_COMPLETED = "COMPLETED"
